import Providers from '@/components/Providers';
import { Space_Mono } from 'next/font/google';
import './globals.css';

const spaceMono = Space_Mono({ subsets: ['vietnamese'], weight: '400' });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={spaceMono.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
